@startuml
skinparam dpi 150
hide footbox

control currentKeyFrameMutex
box "SlamSystem::randomInit"
participant currentKeyFrameMutex
participant slamNode
end box

control activeKeyFramelock
box "DepthMap::initializeRandomly"
participant map
participant activeKeyFramelock
end box

entity frame

slamNode -> currentKeyFrameMutex : lock
activate currentKeyFrameMutex

slamNode -> slamNode: //**currentKeyFrame.reset**//
activate slamNode
deactivate slamNode

slamNode -> map: init randomly

map -> activeKeyFramelock : lock
activate activeKeyFramelock

frame -> frame : //maxGradients//\ninit. all frame-hosted buffers
activate frame
deactivate frame

map -> map: init. \n//**currentDepthMap**//\nfor big gradients
activate map
deactivate map

map <-- activeKeyFramelock : unlock
deactivate activeKeyFramelock




slamNode --> currentKeyFrameMutex : unlock
deactivate currentKeyFrameMutex


@enduml
