@startuml
skinparam dpi 150
hide footbox

entity currentKeyFrame
box "SlamSystem::randomInit"
participant slamNode
participant currentKeyFrame
end box

box "DepthMap::initializeRandomly"
participant map
end box

slamNode -> slamNode : lock\n//**currentKeyFrameMutex**//
activate slamNode #FFBBBB

slamNode --> currentKeyFrame : //**image**//

currentKeyFrame -> currentKeyFrame: //reset()//\nwith newed **Frame**
activate currentKeyFrame
deactivate currentKeyFrame

currentKeyFrame --> map : //**currentKeyFrame**//
map -> currentKeyFrame : //getActiveLock()//
activate currentKeyFrame #FFBBBB

currentKeyFrame --> map : //**activeMutex**//

map --> map : //**activeKeyFramelock**//\n//**activeKeyFrame**//\n//**activeKeyFrameImageData**//
map -> currentKeyFrame : //maxGradients()//

activate currentKeyFrame

currentKeyFrame -> currentKeyFrame : //buildImage()//\n//buildGradients//\n//buildMaxGradients()//\nfor all pry. level

deactivate currentKeyFrame

currentKeyFrame --> map : //**maxGradients**//

activate map
map -> map : init. \n//**currentDepthMap**//\nfor big gradients
deactivate map
map --> currentKeyFrame : //**currentDepthMap**//

currentKeyFrame -> currentKeyFrame : //setDepth()//
activate currentKeyFrame

deactivate currentKeyFrame
deactivate currentKeyFrame

slamNode -> slamNode : unlock
deactivate slamNode


@enduml
