@startuml
skinparam dpi 150
hide footbox

entity trackingNewFrame
entity trackingReference
entity currentKeyFrame
box "SlamSystem::trackFrame"
participant trackingNewFrame
participant trackingReference
participant slamNode
participant currentKeyFrame
end box

box "SE3Tracker::trackFrame"
participant tracker
end box

slamNode --> trackingNewFrame : //**image**//

trackingNewFrame -> trackingNewFrame: init. with\nnewed **Frame**
activate trackingNewFrame
deactivate trackingNewFrame

slamNode -> slamNode : lock\n//**currentKeyFrameMutex**//
activate slamNode #FFBBBB

alt //**currentKeyFrame**// updated
slamNode --> trackingReference : //**currentKeyFrame**//
trackingReference -> trackingReference : //importFrame()//
activate trackingReference
trackingReference -> currentKeyFrame : lock
activate currentKeyFrame
currentKeyFrame --> trackingReference : //**frameID**//\n//**keyframe**//
trackingReference --> currentKeyFrame : unlock
deactivate currentKeyFrame
deactivate trackingReference
end

trackingReference --> slamNode : pose
slamNode --> slamNode : //**trackingReferencePose**//

slamNode -> slamNode : unlock
deactivate slamNode

slamNode -> slamNode : //lock_shared()//\n//**poseConsistencyMutex**//
activate slamNode #FFBBBB

slamNode --> slamNode : //R_{ref}_{trk}//
deactivate slamNode

slamNode -> tracker : frame, keyframe, R_init
tracker -> trackingNewFrame : shared_lock
activate trackingNewFrame

tracker -[#0000FF]-> trackingReference
trackingReference -> trackingReference : //makePointCloud()//
activate trackingReference
trackingReference --> tracker: **posData**\n**pointPosInXYGrid**\n**gradData**\n**colorAndVarData**\n**numData**
deactivate trackingReference

trackingNewFrame --> tracker : gradients\nisGoodOutBuffer

tracker -> tracker : //calcResidualAndBuffers()//
activate tracker
tracker -> tracker : //calcWeightsAndResidual()//

loop settings.maxIts
tracker -> tracker : //calculateWarpUpdate()//
end

tracker --> slamNode : //R_{trk}_{ref}//
deactivate tracker


deactivate trackingNewFrame

@enduml
